# Generated by Django 2.0.6 on 2018-06-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180622_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('author_edit', 'Edit Author fields'),)},
        ),
    ]
